--   AUTHOR:    MICHAL ZAWILSKI

-- Funkcja 1: Wyliczenie kwoty uslugi --

CREATE OR REPLACE FUNCTION LICZ_KWOTA_USLUGA (
NET_ID INT,
TV_ID INT)
RETURN NUMBER IS
KWOTA_NET NUMBER(6,2);
KWOTA_TV NUMBER(6,2);
KWOTA NUMBER (8,2);
BEGIN
    SELECT CENA INTO KWOTA_NET FROM INTERNET WHERE ID=NET_ID;
    SELECT CENA INTO KWOTA_TV FROM TELEWIZJA WHERE ID=TV_ID;
    KWOTA := KWOTA_TV + KWOTA_NET;
    RETURN KWOTA;
END;
/

-- Example --

SET SERVEROUTPUT ON
/
BEGIN
DBMS_OUTPUT.PUT_LINE(LICZ_USLUGA(1,1));
END;
/

-- Funkcja 2:  WYLICZENIE ZALEGLYCH FAKTUR DANEGO KLIENTA --

CREATE OR REPLACE FUNCTION ILE_ZALEGLYCH_FAKTUR(
ID_KLIENT INT
)
RETURN INT IS 
    V_COUNT INT;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM FAKTURY WHERE KLIENT_ID=ID_KLIENT AND CZY_OPLACONA ='F';
    RETURN V_COUNT;
END;
/

-- EXAMPLE --

SET SERVEROUTPUT ON
/
BEGIN
DBMS_OUTPUT.PUT_LINE(ILE_ZALEGLYCH_FAKTUR(104));
END;
/


-- FUNKCJA 3: ROCZNY DOCHOD NA PODSTAWIE OPLACONYCH FAKTUR --

CREATE OR REPLACE FUNCTION PRZYCHOD_ROK (ROK INT) 
RETURN NUMBER IS
V_SUM NUMBER;
BEGIN
    SELECT SUM(NALEZNOSC) INTO V_SUM FROM FAKTURY WHERE FAKTURY.ROK=ROK AND CZY_OPLACONA = 'T';
    RETURN V_SUM;
END;
/

-- EXAMPLE --

SET SERVEROUTPUT ON
/
BEGIN
DBMS_OUTPUT.PUT_LINE(PRZYCHOD_ROK(2019));
END;
/

-- FUNKCJA 4: WYLICZ ZALEGLOSC W SPLACIE --

CREATE OR REPLACE FUNCTION LICZ_ZALEGLOSC(KLIENT NUMBER)
RETURN NUMBER IS
    V_ZALEGLOSC NUMBER;
    V_NALEZNOSC NUMBER;
    V_WPLATY NUMBER;
BEGIN
    SELECT NALEZNOSC INTO V_NALEZNOSC FROM ZESTAWIENIE_NALEZNOSCI_WPLATY WHERE KLIENT_ID=KLIENT;
    SELECT WPLATY INTO V_WPLATY FROM ZESTAWIENIE_NALEZNOSCI_WPLATY WHERE KLIENT_ID=KLIENT;
    V_ZALEGLOSC := V_NALEZNOSC - V_WPLATY;
    RETURN V_ZALEGLOSC;
END;
/
SELECT KLIENT_ID FROM ZESTAWIENIE_NALEZNOSCI_WPLATY;
-- EXAMPLE --

SET SERVEROUTPUT ON
/
BEGIN
DBMS_OUTPUT.PUT_LINE(LICZ_ZALEGLOSC(103));
END;
/

-- FUNCKJA 5: OBLICZENIE ILOSCI KANALOW-- 

CREATE OR REPLACE FUNCTION ILE_KANALOW(ID_PAKIET INT)
RETURN NUMBER IS
    V_SUM NUMBER;
BEGIN
    SELECT SUM(ID) INTO V_SUM FROM KANALY_TV
    WHERE PAKIET_TV_ID = ID_PAKIET;
    RETURN V_SUM;
END;

SET SERVEROUTPUT ON
/
BEGIN
DBMS_OUTPUT.PUT_LINE(ILE_KANALOW(1));
END;
/

-- FUNCTION 6: LOGOWANIE --

CREATE OR REPLACE FUNCTION loguj(p_username VARCHAR2, p_password VARCHAR2)
RETURN BOOLEAN
AS
	tmp VARCHAR(1);
BEGIN
	SELECT 1 INTO TMP 
	  FROM konto 
	  WHERE UPPER(login) = UPPER(p_username) AND haslo = p_password;
	RETURN TRUE;
	EXCEPTION
	WHEN NO_DATA_FOUND
	THEN
		RETURN FALSE;
END loguj;
