--   AUTHOR:    MICHAL ZAWILSKI

-- PROCEDURA 1: INSERT WPLATY Z DATA POBRANA Z SYSTEMU --

CREATE OR REPLACE PROCEDURE NOWA_PLATNOSC (
    KLIENT_ID PLATNOSCI.FAKTURY_KLIENT_ID%TYPE,
    KWOTA_WPLACONA PLATNOSCI.KWOTA_WPLACONA%TYPE) 
IS
    V_ROK INT;
    V_MIESIAC INT;
BEGIN
    V_MIESIAC := EXTRACT (MONTH FROM SYSDATE);
    V_ROK := EXTRACT (YEAR FROM SYSDATE);
    INSERT INTO PLATNOSCI (FAKTURY_KLIENT_ID, FAKTURY_ROK, FAKTURY_MIESIAC, KWOTA_WPLACONA) 
    VALUES (KLIENT_ID, V_ROK, V_MIESIAC, KWOTA_WPLACONA);
END;

-- EXECUTE EXAMPLE -- 

-- SELECT * FROM PLATNOSCI; 
-- EXECUTE(103, 20);
-- SELECT * FROM PLATNOSCI;

-- PROCEDURA 2: UPDATE PROCENTOWA PODWYZKA CENY USLUG ZA INTERNET --

CREATE OR REPLACE PROCEDURE UPDATE_CENA_INTERNET (
    P_ID INTERNET.ID%TYPE,
    P_PROCENT INT)
IS
BEGIN
    UPDATE INTERNET
    SET INTERNET.CENA = INTERNET.CENA * (1+P_PROCENT)/100
    WHERE P_ID = INTERNET.ID;
END;

-- EXAMPLE --

-- SELECT * FROM INTERNET WHERE ID=1;
-- EXECUTE UPDATE_CENA_INTERNET;
-- SELECT * FROM INTERNET WHERE ID=1;

-- PROCEDURA 3: ZAMKNIECIE ZGLOSZENIA --

CREATE OR REPLACE PROCEDURE ZAMKNIJ_ZGLOSZENIE(
V_ID INT) 
IS
BEGIN
    UPDATE TICKETS 
    SET ZAKONCZONE='T'
    WHERE ID=V_ID;
END;

-- EXAMPLE --

--SELECT * FROM TICKETS WHERE ID = 4;
--EXECUTE ZAMKNIJ_ZGLOSZENIE(4);
--SELECT * FROM TICKETS WHERE ID = 4;

-- PROCEDURA 4: DODANIE ZGLOSZENIA (DZIALA Z BEFORE_INSERT_TRIGGER) --

CREATE OR REPLACE PROCEDURE DODAJ_ZGLOSZENIE (
V_TYP INT,
V_OPIS VARCHAR,
V_KLIENT_ID INT)
IS
BEGIN
    INSERT INTO TICKETS (TYP_ZGLOSZENIA, OPIS, ZGLASZAJACY) 
    VALUES (V_TYP, V_OPIS, V_KLIENT_ID);
END;
/

-- EXAMPLE --

EXECUTE DODAJ_ZGLOSZENIE (1, 'COS SIE STALO', 103)

-- PROCEDURA 5: DODANIE USLUGI I WYLICZENIE KWOTY ZA POMOCA FUNKCJI --

CREATE OR REPLACE PROCEDURE DODAJ_USLUGA (NET_ID INT, TV_ID INT)
IS
BEGIN
    INSERT INTO USLUGI (INTERNET_ID, TELEWIZJA_ID, KWOTA_USLUGI) 
    VALUES (NET_ID, TV_ID, LICZ_USLUGA(NET_ID, TV_ID));
END;

-- EXAMPLE --

EXECUTE DODAJ_USLUGA (3, 4)