--   AUTHOR:    MICHAL ZAWILSKI

CREATE OR REPLACE PACKAGE PROJEKT IS   
    
    FUNCTION LICZ_KWOTA_USLUGA (NET_ID INT, TV_ID INT) RETURN NUMBER;
    FUNCTION ILE_ZALEGLYCH_FAKTUR (ID_KLIENT INT) RETURN INT;
    FUNCTION PRZYCHOD_ROK (ROK INT) RETURN NUMBER;
    FUNCTION ILE_KANALOW(ID_PAKIET INT) RETURN NUMBER;
    FUNCTION LICZ_ZALEGLOSC(KLIENT NUMBER) RETURN NUMBER;
    FUNCTION LOGUJ (P_USERNAME VARCHAR2, P_PASSWORD VARCHAR2) RETURN BOOLEAN;    

    PROCEDURE NOWA_PLATNOSC(
    KLIENT_ID PLATNOSCI.FAKTURY_KLIENT_ID%TYPE,
    KWOTA_WPLACONA PLATNOSCI.KWOTA_WPLACONA%TYPE);
    
    PROCEDURE UPDATE_CENA_INTERNET (
    P_ID INTERNET.ID%TYPE,
    P_PROCENT INT);
    PROCEDURE UPDATE_CENA_INTERNET ( P_PROCENT INT);
    
    PROCEDURE ZAMKNIJ_ZGLOSZENIE(V_ID INT); 
    
    PROCEDURE DODAJ_USLUGA (NET_ID INT, TV_ID INT);
    
    PROCEDURE DODAJ_ZGLOSZENIE (
    V_TYP INT,
    V_OPIS VARCHAR,
    V_KLIENT_ID INT);

END PROJEKT;
/

CREATE OR REPLACE PACKAGE BODY PROJEKT IS

-- FUNCTIONS --

FUNCTION LICZ_KWOTA_USLUGA (
NET_ID INT,
TV_ID INT)
RETURN NUMBER IS
KWOTA_NET NUMBER(6,2);
KWOTA_TV NUMBER(6,2);
KWOTA NUMBER (8,2);
BEGIN
    SELECT CENA INTO KWOTA_NET FROM INTERNET WHERE ID=NET_ID;
    SELECT CENA INTO KWOTA_TV FROM TELEWIZJA WHERE ID=TV_ID;
    KWOTA := KWOTA_TV + KWOTA_NET;
    RETURN KWOTA;
END;

FUNCTION ILE_ZALEGLYCH_FAKTUR(
ID_KLIENT INT
)
RETURN INT IS 
    V_COUNT INT;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM FAKTURY WHERE KLIENT_ID=ID_KLIENT AND CZY_OPLACONA ='F';
    RETURN V_COUNT;
END;

FUNCTION PRZYCHOD_ROK (ROK INT) 
RETURN NUMBER IS
V_SUM NUMBER;
BEGIN
    SELECT SUM(NALEZNOSC) INTO V_SUM FROM FAKTURY WHERE FAKTURY.ROK=ROK AND CZY_OPLACONA = 'T';
    RETURN V_SUM;
END;


FUNCTION LICZ_ZALEGLOSC(KLIENT NUMBER)
RETURN NUMBER IS
    V_ZALEGLOSC NUMBER;
    V_NALEZNOSC NUMBER;
    V_WPLATY NUMBER;
BEGIN
    SELECT NALEZNOSC INTO V_NALEZNOSC FROM ZESTAWIENIE_NALEZNOSCI_WPLATY WHERE KLIENT_ID=KLIENT;
    SELECT WPLATY INTO V_WPLATY FROM ZESTAWIENIE_NALEZNOSCI_WPLATY WHERE KLIENT_ID=KLIENT;
    V_ZALEGLOSC := V_NALEZNOSC - V_WPLATY;
    RETURN V_ZALEGLOSC;
END;

FUNCTION ILE_KANALOW(ID_PAKIET INT)
RETURN NUMBER IS
    V_SUM NUMBER;
BEGIN
    SELECT SUM(ID) INTO V_SUM FROM KANALY_TV
    WHERE PAKIET_TV_ID = ID_PAKIET;
    RETURN V_SUM;
END;


FUNCTION loguj(p_username VARCHAR2, p_password VARCHAR2)
RETURN BOOLEAN
AS
	tmp VARCHAR(1);
BEGIN
	SELECT 1 INTO TMP 
	  FROM konto 
	  WHERE UPPER(login) = UPPER(p_username) AND haslo = p_password;
	RETURN TRUE;
	EXCEPTION
	WHEN NO_DATA_FOUND
	THEN
		RETURN FALSE;
END loguj;
-- PROCEDURES --

PROCEDURE NOWA_PLATNOSC (
    KLIENT_ID PLATNOSCI.FAKTURY_KLIENT_ID%TYPE,
    KWOTA_WPLACONA PLATNOSCI.KWOTA_WPLACONA%TYPE) 
IS
    V_ROK INT;
    V_MIESIAC INT;
BEGIN
    V_MIESIAC := EXTRACT (MONTH FROM SYSDATE);
    V_ROK := EXTRACT (YEAR FROM SYSDATE);
    INSERT INTO PLATNOSCI (FAKTURY_KLIENT_ID, FAKTURY_ROK, FAKTURY_MIESIAC, KWOTA_WPLACONA) 
    VALUES (KLIENT_ID, V_ROK, V_MIESIAC, KWOTA_WPLACONA);
END;


PROCEDURE UPDATE_CENA_INTERNET (
    P_ID INTERNET.ID%TYPE,
    P_PROCENT INT)
IS
BEGIN
    UPDATE INTERNET
    SET INTERNET.CENA = INTERNET.CENA * (1+P_PROCENT)/100
    WHERE P_ID = INTERNET.ID;
END;

PROCEDURE UPDATE_CENA_INTERNET (P_PROCENT INT)
IS
BEGIN
    UPDATE INTERNET
    SET INTERNET.CENA = INTERNET.CENA * (1+P_PROCENT)/100;
END;

PROCEDURE ZAMKNIJ_ZGLOSZENIE(
V_ID INT) 
IS
BEGIN
    UPDATE TICKETS 
    SET ZAKONCZONE='T'
    WHERE ID=V_ID;
END;

PROCEDURE DODAJ_USLUGA (NET_ID INT, TV_ID INT)
IS
BEGIN
    INSERT INTO USLUGI (INTERNET_ID, TELEWIZJA_ID, KWOTA_USLUGI) 
    VALUES (NET_ID, TV_ID, LICZ_USLUGA(NET_ID, TV_ID));
END;

PROCEDURE DODAJ_ZGLOSZENIE (
V_TYP INT,
V_OPIS VARCHAR,
V_KLIENT_ID INT)
IS
BEGIN
    INSERT INTO TICKETS (TYP_ZGLOSZENIA, OPIS, ZGLASZAJACY) 
    VALUES (V_TYP, V_OPIS, V_KLIENT_ID);
END;


END PROJEKT;